"""add_job_application_skill_assessment_and_learning_path_tables

Revision ID: ced9a4b2a36f
Revises: 1dcbf6c9b428
Create Date: 2025-03-09 23:38:25.003439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced9a4b2a36f'
down_revision: Union[str, None] = '1dcbf6c9b428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('skill_name', sa.String(length=100), nullable=False, comment='技能名称'),
    sa.Column('skill_category', sa.String(length=50), nullable=True, comment='技能类别'),
    sa.Column('proficiency_level', sa.Float(), nullable=True, comment='熟练度评分'),
    sa.Column('assessment_type', sa.String(length=50), nullable=True, comment='评估类型：self-自评，test-测试，interview-面试，ai-AI评估'),
    sa.Column('assessment_details', sa.JSON(), nullable=True, comment='评估详情'),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True, comment='改进建议'),
    sa.Column('next_level_requirements', sa.JSON(), nullable=True, comment='下一等级要求'),
    sa.Column('verified', sa.Boolean(), nullable=True, comment='是否经过验证'),
    sa.Column('verifier_id', sa.Integer(), nullable=True, comment='验证人ID'),
    sa.Column('verification_date', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='申请人ID'),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='工作ID'),
    sa.Column('resume_id', sa.Integer(), nullable=True, comment='简历ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='申请状态：pending-待处理，reviewing-审核中，accepted-已接受，rejected-已拒绝'),
    sa.Column('cover_letter', sa.Text(), nullable=True, comment='求职信'),
    sa.Column('interview_time', sa.DateTime(), nullable=True, comment='面试时间'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='面试反馈'),
    sa.Column('match_score', sa.Integer(), nullable=True, comment='匹配分数'),
    sa.Column('analysis_report', sa.JSON(), nullable=True, comment='分析报告'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('target_job_id', sa.Integer(), nullable=True, comment='目标职位ID'),
    sa.Column('target_career_id', sa.Integer(), nullable=True, comment='目标职业ID'),
    sa.Column('current_level', sa.String(length=50), nullable=True, comment='当前水平'),
    sa.Column('target_level', sa.String(length=50), nullable=True, comment='目标水平'),
    sa.Column('required_skills', sa.JSON(), nullable=True, comment='需要掌握的技能'),
    sa.Column('learning_steps', sa.JSON(), nullable=True, comment='学习步骤'),
    sa.Column('timeline', sa.JSON(), nullable=True, comment='时间线规划'),
    sa.Column('resources', sa.JSON(), nullable=True, comment='学习资源'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='完成进度(0-100)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('completion_date', sa.DateTime(), nullable=True, comment='预计完成时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['target_career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['target_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_paths')
    op.drop_table('job_applications')
    op.drop_table('skill_assessments')
    # ### end Alembic commands ###
