"""add_resume_table

Revision ID: 1dcbf6c9b428
Revises: d7ea3a5ac2d5
Create Date: 2025-03-09 23:34:30.104099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcbf6c9b428'
down_revision: Union[str, None] = 'd7ea3a5ac2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='简历标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='简历内容'),
    sa.Column('file_url', sa.String(length=255), nullable=True, comment='简历文件URL'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='简历状态：draft-草稿，submitted-已提交，approved-已通过，rejected-已拒绝'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    # ### end Alembic commands ###
